import { getFileVisualKind } from "@/utils/files";

export interface FileIconMeta {
  icon: string;
  kind: string;
  source: "element" | "material";
  tone: string;
}

export const FILE_ICON_META: Record<string, FileIconMeta> = {
  astro: { icon: "astro", kind: "astro", source: "material", tone: "code" },
  audio: { icon: "audio", kind: "audio", source: "element", tone: "media" },
  binary: { icon: "binary", kind: "binary", source: "element", tone: "binary" },
  c: { icon: "c", kind: "c", source: "material", tone: "code" },
  clojure: { icon: "clojure", kind: "clojure", source: "material", tone: "code" },
  cmake: { icon: "cmake", kind: "cmake", source: "material", tone: "repo" },
  config: { icon: "settings", kind: "config", source: "material", tone: "repo" },
  console: { icon: "console", kind: "console", source: "material", tone: "repo" },
  cpp: { icon: "cpp", kind: "cpp", source: "material", tone: "code" },
  csharp: { icon: "csharp", kind: "csharp", source: "material", tone: "code" },
  css: { icon: "css", kind: "css", source: "material", tone: "code" },
  cuda: { icon: "cuda", kind: "cuda", source: "material", tone: "code" },
  dart: { icon: "dart", kind: "dart", source: "material", tone: "code" },
  database: { icon: "database", kind: "database", source: "material", tone: "data" },
  docker: { icon: "docker", kind: "docker", source: "material", tone: "repo" },
  document: { icon: "document", kind: "document", source: "material", tone: "docs" },
  elixir: { icon: "elixir", kind: "elixir", source: "material", tone: "code" },
  erlang: { icon: "erlang", kind: "erlang", source: "material", tone: "code" },
  folder: { icon: "folder", kind: "folder", source: "element", tone: "folder" },
  font: { icon: "font", kind: "font", source: "material", tone: "media" },
  fortran: { icon: "fortran", kind: "fortran", source: "material", tone: "code" },
  git: { icon: "git", kind: "git", source: "material", tone: "repo" },
  go: { icon: "go", kind: "go", source: "material", tone: "code" },
  gradle: { icon: "gradle", kind: "gradle", source: "material", tone: "repo" },
  graphql: { icon: "graphql", kind: "graphql", source: "material", tone: "repo" },
  groovy: { icon: "groovy", kind: "groovy", source: "material", tone: "code" },
  haskell: { icon: "haskell", kind: "haskell", source: "material", tone: "code" },
  helm: { icon: "helm", kind: "helm", source: "material", tone: "repo" },
  html: { icon: "html", kind: "html", source: "material", tone: "code" },
  image: { icon: "image", kind: "image", source: "material", tone: "media" },
  java: { icon: "java", kind: "java", source: "material", tone: "code" },
  javascript: { icon: "javascript", kind: "javascript", source: "material", tone: "code" },
  json: { icon: "json", kind: "json", source: "material", tone: "repo" },
  julia: { icon: "julia", kind: "julia", source: "material", tone: "code" },
  jupyter: { icon: "jupyter", kind: "jupyter", source: "material", tone: "data" },
  kotlin: { icon: "kotlin", kind: "kotlin", source: "material", tone: "code" },
  kubernetes: { icon: "kubernetes", kind: "kubernetes", source: "material", tone: "repo" },
  less: { icon: "less", kind: "less", source: "material", tone: "code" },
  license: { icon: "license", kind: "license", source: "material", tone: "docs" },
  lock: { icon: "lock", kind: "lock", source: "material", tone: "repo" },
  log: { icon: "log", kind: "log", source: "material", tone: "repo" },
  lua: { icon: "lua", kind: "lua", source: "material", tone: "code" },
  makefile: { icon: "makefile", kind: "makefile", source: "material", tone: "repo" },
  markdown: { icon: "markdown", kind: "markdown", source: "material", tone: "docs" },
  matlab: { icon: "matlab", kind: "matlab", source: "material", tone: "data" },
  maven: { icon: "maven", kind: "maven", source: "material", tone: "repo" },
  nginx: { icon: "nginx", kind: "nginx", source: "material", tone: "repo" },
  nim: { icon: "nim", kind: "nim", source: "material", tone: "code" },
  npm: { icon: "npm", kind: "npm", source: "material", tone: "repo" },
  onnx: { icon: "onnx", kind: "onnx", source: "material", tone: "model" },
  pdf: { icon: "pdf", kind: "pdf", source: "material", tone: "media" },
  perl: { icon: "perl", kind: "perl", source: "material", tone: "code" },
  php: { icon: "php", kind: "php", source: "material", tone: "code" },
  pnpm: { icon: "pnpm", kind: "pnpm", source: "material", tone: "repo" },
  powershell: { icon: "powershell", kind: "powershell", source: "material", tone: "repo" },
  prisma: { icon: "prisma", kind: "prisma", source: "material", tone: "repo" },
  proto: { icon: "proto", kind: "proto", source: "material", tone: "code" },
  python: { icon: "python", kind: "python", source: "material", tone: "code" },
  pytorch: { icon: "pytorch", kind: "pytorch", source: "material", tone: "model" },
  r: { icon: "r", kind: "r", source: "material", tone: "code" },
  racket: { icon: "racket", kind: "racket", source: "material", tone: "code" },
  react: { icon: "react", kind: "react", source: "material", tone: "code" },
  readme: { icon: "readme", kind: "readme", source: "material", tone: "docs" },
  ruby: { icon: "ruby", kind: "ruby", source: "material", tone: "code" },
  rust: { icon: "rust", kind: "rust", source: "material", tone: "code" },
  sass: { icon: "sass", kind: "sass", source: "material", tone: "code" },
  scala: { icon: "scala", kind: "scala", source: "material", tone: "code" },
  solidity: { icon: "solidity", kind: "solidity", source: "material", tone: "code" },
  svg: { icon: "svg", kind: "svg", source: "material", tone: "media" },
  svelte: { icon: "svelte", kind: "svelte", source: "material", tone: "code" },
  swift: { icon: "swift", kind: "swift", source: "material", tone: "code" },
  table: { icon: "table", kind: "table", source: "material", tone: "data" },
  tailwindcss: { icon: "tailwindcss", kind: "tailwindcss", source: "material", tone: "repo" },
  terraform: { icon: "terraform", kind: "terraform", source: "material", tone: "repo" },
  toml: { icon: "toml", kind: "toml", source: "material", tone: "repo" },
  typescript: { icon: "typescript", kind: "typescript", source: "material", tone: "code" },
  video: { icon: "video", kind: "video", source: "element", tone: "media" },
  vue: { icon: "vue", kind: "vue", source: "material", tone: "code" },
  webassembly: { icon: "webassembly", kind: "webassembly", source: "material", tone: "code" },
  xml: { icon: "xml", kind: "xml", source: "material", tone: "repo" },
  yaml: { icon: "yaml", kind: "yaml", source: "material", tone: "repo" },
  yarn: { icon: "yarn", kind: "yarn", source: "material", tone: "repo" },
  zig: { icon: "zig", kind: "zig", source: "material", tone: "code" },
  zip: { icon: "zip", kind: "zip", source: "material", tone: "data" }
};

export function getFileIconMeta(path: string, entryType?: string): FileIconMeta {
  const kind = getFileVisualKind(path, entryType);
  return FILE_ICON_META[kind] || FILE_ICON_META.document;
}
