#!/usr/bin/env python
"""
Generate optimized PyInstaller spec file with all necessary resource files
"""

import argparse
import sys
from typing import List, Sequence, Tuple


PROJECT_NAME = 'hubvault'
CLI_ENTRY = 'hubvault_cli.py'

EXCLUDED_MODULES: Sequence[str] = [
    # GUI, data-science, and notebook stacks that are not used by the CLI.
    'tkinter',
    'matplotlib',
    'numpy',
    'pandas',
    'scipy',
    'IPython',
    'jupyter',
    'notebook',
    # Test and documentation helpers that should never ship in the standalone build.
    'pytest',
    'unittest',
    'doctest',
    'pydoc',
    # Packaging and installer tooling that is only present in the build environment.
    'PyInstaller',
    '_pyinstaller_hooks_contrib',
    'altgraph',
    'macholib',
    'pefile',
    'win32ctypes',
    'distutils',
    'setuptools',
    'pip',
    # Icon generation dependencies observed in Release Test environments.
    'PIL',
    'cairosvg',
    'cairocffi',
    'cffi',
    '_cffi_backend',
    'cssselect2',
    'defusedxml',
    'tinycss2',
    'webencodings',
    # Miscellaneous stdlib/test helpers that are not required by the CLI runtime.
    'xmlrpc',
    'http.server',
    '_pytest',
    'py',
]


def collect_datas() -> List[Tuple[str, str]]:
    """Collect data files that need to be packaged."""
    datas: List[Tuple[str, str]] = []

    try:
        from tools.resources import get_resource_files

        for src_file, dst_dir in get_resource_files():
            datas.append((src_file, dst_dir))
    except Exception as err:
        print(f"Warning: Could not collect resources from tools.resources: {err}", file=sys.stderr)

    return datas


def generate_spec():
    """Generate spec file content."""
    datas = collect_datas()
    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-

# This file is automatically generated by tools/generate_spec.py

a = Analysis(
    [{CLI_ENTRY!r}],
    pathex=[],
    binaries=[],
    datas={datas!r},
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes={EXCLUDED_MODULES!r},
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={PROJECT_NAME!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''

    return spec_content, len(datas)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Generate optimized PyInstaller spec file with all necessary resource files'
    )
    parser.add_argument(
        '-o', '--output',
        default=f'{PROJECT_NAME}.spec',
        help=f'Output spec file path (default: {PROJECT_NAME}.spec)'
    )
    args = parser.parse_args()

    spec_content, data_count = generate_spec()

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(spec_content)

    print(f"Generated {args.output} with {data_count} data files")
